title: Karenina Arch
description: Site para divulgação de portfólio de web design e desenvolvedora front end

url: https://zkkarenina.github.io/
paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Inicio
    url: /index.html
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: ZKKarenina
  twitter: karenina_arch
  email: fleshpaulo@gmail.com
  linkedin:

google_analytics: ""

disqus:
    shortname: Karenina
